language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="exif meson gcc"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && ninja -C build test"

script:
- echo BUILDS PASSED
